language: generic
sudo: required
services:
  - docker

# Need super user permisions.
# let travis use a copy of docker

before_install:
  - docker build -t kazamoney/docker-config -f Dockerfile.dev .
script: 
  - docker run -e CI=true kazamoney/docker-config npm run test
  # - docker run kazamoney/docker-config npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-682004725265"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY